### ISSUE TITLE
Oauth2 problem 

### ISSUE THREAD

**Issue by rich1990** [ddeboer/imap#538] opened 2022-07-08 07:33 UTC
Hello, Office365 is starting to require Oauth2 authentication, there is any way to implement this kind of authentication? or there is any plan in order to implement this?

**Comment by Slamdunk** [comment] 2022-07-08 07:39
Duplicate of https://github.com/ddeboer/imap/issues/443

The issue is not in this library, but in `ext-imap`: https://bugs.php.net/bug.php?id=64039

**Closed by Slamdunk** 2022-07-08 07:39 UTC
Labels: feature request
