### ISSUE TITLE
Uncaught Error: Class 'Ddeboer\imap\Server' not found

### ISSUE THREAD

**Issue by Haqz** [ddeboer/imap#348] opened 2018-05-27 08:48 UTC
I have error when i installed this by composer, any reasons why?

`Uncaught Error: Class 'Ddeboer\imap\Server' not found`

**Comment by Slamdunk** [comment] 2018-05-28 08:00
Duplicate of https://github.com/ddeboer/imap/issues/314

**Closed by Slamdunk** 2018-05-28 08:00 UTC
