### ISSUE TITLE
Missing encoding

### ISSUE THREAD

**Issue by petraeus** [ddeboer/imap#159] opened 2017-06-26 18:25 UTC
PHP Notice:  Undefined offset: 6 in 

~/vendor/ddeboer/imap/src/Message/Part.php on line 221

**Comment by Slamdunk** [comment] 2017-09-22 08:42
Hi, can you provide example for this bug?

**Comment by Slamdunk** [comment] 2017-09-22 09:24
Duplicate of #123

**Comment by Slamdunk** [comment] 2017-09-28 08:08
Closed by #197 thank you

**Closed by Slamdunk** 2017-09-28 08:08 UTC
Labels: bug, duplicate
