### ISSUE TITLE
$message->getAttachments() does not return anything, even though a message has at least one attachment

### ISSUE THREAD

**Issue by raulp** [ddeboer/imap#71] opened 2015-01-28 20:30 UTC
Hey

When calling getAttachments, i don't get anything back
Upon doing some research, i saw that the function getParts() is not returning the parts as instance of Message\Attachments, but the getAttachments() function is looking for that
Looking further in the getParts function i saw that my parts don't show up a disposition ( which is why the parts are returned as a Part instead of an Attachment instance )

Here's a gist with the array returned by parseStructure() for all the elements of my email:
https://gist.github.com/raulp/ce7236054284e751f713

Let me know if you need any other info ...
Thank you

**Comment by ddeboer** [comment] 2015-01-29 06:22
Closing as a duplicate of #55. Thanks for reporting though, I understand this is a real issue and fix it soon.

**Closed by ddeboer** 2015-01-29 06:22 UTC

**Comment by raulp** [comment] 2015-01-29 06:24
Ah, sorry, read that, but wanted to provide more insight of what i found and for my specific case, just to help
So if you need anything from my end, like messages and stuff, let me know

Thanks !!

**Comment by ddeboer** [comment] 2015-01-29 06:25
Cool, thank you @raulp!
