### ISSUE TITLE
Searching subject with apostrophe

### ISSUE THREAD

**Issue by billynoah** [ddeboer/imap#355] opened 2018-06-20 02:37 UTC
Is it possible to search subject with apostrophe?

Example:
```php
$subject = "Bob's Grand Opening";
$search = new SearchExpression();
$search->addCondition(new Subject($subject));
```

This fails for me and no amount of escaping seems to help.  Best workaround I've come up with is to do:
```php
$subjects = ["Bob","Grand Opening"];
$search = new SearchExpression();
foreach ($subjects as $subject) {
	$search->addCondition(new Subject($subject));
}
```
Which is not exactly what I want to search, but often close enough.  Is this a shortcoming of php imap?  Is there a way to search strings containing single quotes?

**Comment by Slamdunk** [comment] 2018-06-20 09:12
As shown in https://github.com/ddeboer/imap/pull/356/files I tried to reproduce the bug but the build succeed.

Which IMAP server do you use?

**Comment by billynoah** [comment] 2018-06-20 12:40
Gmail.

**Comment by Slamdunk** [comment] 2018-06-20 13:57
Hi, I've tested the bug on GMail and in fact is present.

I've googled aobut it, and I think we cannot support apostrophe search without dropping spaces one, which is much more widely use.

You can always use [RawExpression](https://github.com/ddeboer/imap/blob/master/src/Search/RawExpression.php) to write your own raw search expression and play with escaping :wink:

**Comment by billynoah** [comment] 2018-06-20 16:38
Thanks - can you make any suggestion about how to write a raw search expression that might work with gmail?

**Comment by Slamdunk** [comment] 2018-06-21 07:20
You can take the output of the main expressions and use it as the raw one:

```php
$subjectSearch = new Ddeboer\Imap\Search\Text\Subject("Bob's Grand Opening");
var_export($subjectSearch->toString());
// Output: 'SUBJECT "Bob\'s Grand Opening"'

$rawExpression = new Ddeboer\Imap\Search\RawExpression('SUBJECT "Bob\'s Grand Opening"');
```

**Comment by billynoah** [comment] 2018-06-21 13:21
Thanks very much!

**Comment by Slamdunk** [comment] 2018-06-21 13:23
If you find a way to get apostrophe functioning, please post here the raw expression, so I can try to implement it in the project as well

**Comment by Slamdunk** [comment] 2018-12-04 09:17
@billynoah have you found a way to handle apostrophes?

**Comment by billynoah** [comment] 2018-12-04 16:15
I don't believe so.  I think I ended doing more general search and iterating over results manually.

**Comment by Slamdunk** [comment] 2018-12-05 07:18
Ok, I'm closing this because I can't see a solution at the moment.
Anyone feels free to reopen this PR with any kind of solution.

**Closed by Slamdunk** 2018-12-05 07:18 UTC
Labels: bug, wontfix
