### ISSUE TITLE
How to get message id?

### ISSUE THREAD

**Issue by agoenks29D** [ddeboer/imap#411] opened 2019-05-04 13:48 UTC
I try to make mail saved to **INBOX.sent** folder if sent. In readme,md you just write :
```php
$mailbox = $connection->getMailbox('Sent');
$mailbox->addMessage($messageMIME, '\\Seen');
```

and i try on my webmail send to get example of mime, and i get this result : 

MIME-Version: 1.0
Content-Type: text/plain; charset=US-ASCII;
 format=flowed
Content-Transfer-Encoding: 7bit
Date: Sat, 04 May 2019 18:51:29 +0700
From: developer2@mydomain.id
To: agungmasda29@gmail.com
Subject: compose from dev2
Message-ID: <a573765ff1f6a1805d9c1605ddf3022a@mydomain.id>
X-Sender: developer2@mydomain.id
User-Agent: Roundcube Webmail/1.3.6

How i can get Message-ID: ? if saved to sent folder? i just get boolean data when it saved

**Comment by Slamdunk** [comment] 2019-05-23 10:26
Duplicate of https://github.com/ddeboer/imap/issues/391

**Closed by Slamdunk** 2019-05-23 10:26 UTC
Labels: question
