### ISSUE TITLE
Mailbox name string

### ISSUE THREAD

**Issue by ufee** [ddeboer/imap#390] opened 2019-01-11 09:07 UTC
In some cases, this code:
`$imap->getMailboxes();`

Throw error:
> .../some/script.php: Ddeboer\Imap\Connection->getMailboxes()
> .../vendor/ddeboer/imap/src/Connection.php(95): Ddeboer\Imap\Connection->getMailbox(integer '1')
> in .../vendor/ddeboer/imap/src/Connection.php(125):
> Argument 1 passed to Ddeboer\Imap\Connection::getMailbox() must be of the type string, integer given, called in .../vendor/ddeboer/imap/src/Connection.php on line 95

Because method getMailbox required string Mailbox name, but method initMailboxNames push string or integer names to $this->mailboxNames.

May be replace:
`$name = \mb_convert_encoding(\str_replace($this->server, '', $mailboxInfo->name), 'UTF-8', 'UTF7-IMAP');`
to:
`$name = (string)\mb_convert_encoding(\str_replace($this->server, '', $mailboxInfo->name), 'UTF-8', 'UTF7-IMAP')`
?

**Comment by Slamdunk** [comment] 2019-01-11 09:12
Already fixed in #381 and released in v1.6.0 (available for PHP > 7.1 only)

**Comment by Slamdunk** [comment] 2019-01-11 09:14
Duplicate of #380

**Closed by Slamdunk** 2019-01-11 09:14 UTC
